import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { ThemeProvider } from "@/components/tymeMode/theme-provider";
import { Toaster } from "@/components/ui/toaster";
import { Reduxprovider } from "@/provider/redux-procider";
import { NextProvider } from "@/provider/next-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextProvider>
          <Reduxprovider>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
              <div className=" flex flex-col justify-between min-h-screen ">
                <div>
                  <Header />
                  {children}
                </div>
                <Footer />
              </div>
              <Toaster />
            </ThemeProvider>
          </Reduxprovider>
        </NextProvider>
      </body>
    </html>
  );
}
